### ISSUE TITLE
Shadow on Android 7.0

### ISSUE THREAD

**Issue by bios90** [ZieIony/Carbon#406]
On android 9 all shadows are shown as it should. But on Android 7.0 no shadows at all. Can i somehow fix this?
![photo_2020-04-01 16 39 25](https://user-images.githubusercontent.com/38374129/78143816-6da87000-7437-11ea-8fee-236cc1422c2e.jpeg)
![photo_2020-04-01 16 39 29](https://user-images.githubusercontent.com/38374129/78143828-6f723380-7437-11ea-977b-e40e11c23aee.jpeg)

**Comment by ZieIony** [comment]
Are you specifying a custom shadow color? It's the only difference between Android 7 and 9 I can think of. If you're using the release version from Maven, you can try the latest commit from the master branch. I didn't release for a long time and there's a couple of fixes related to shadows there.

**Comment by bios90** [comment]
i use this style 
    `<carbon.widget.LinearLayout
            app:carbon_elevation="30dp"
            app:carbon_elevationShadowColor="#660C0C0C"
            android:background="@android:color/white"/>`

**Comment by ZieIony** [comment]
Custom shadow colors are supported on Android 9 natively and on Android 7 are backported. That backport is quite complex and I changed it a couple of times. On `0.16.0` it was rendered using RenderScript and custom 9-patches, and now it simply uses `MaterialShapeDrawable` from Android Jetpack. Also, elevation in the RenderScript implementation was clamped to [0.0f:25.0f] due to technical limitations.

If you don't need that custom color, delete it and plain, black shadows should work on both platforms. If you need colored shadows and you're using `0.16.0`, try using the most recent commit (although it may break other things as there were many changes in other things too). If you're using the most recent commit already then it's a bug and I'll try to fix it.

**Comment by bios90** [comment]
Thanks for quick and explained answer answer! Will try)

**Comment by bios90** [comment]
The problem was in `carbon_elevationShadowColor` attribute. In my case it is not working on api 25, but works well on api 28. To solve this problem i made special style for api 28 where i set `carbon_elevationShadowColor` attribute, while lower versions do not use this attribute.

**Comment by ZieIony** [comment]
That's not a solution but a workaround. Could you please share the version you're using? I'm curious if it's something in the current version or an old bug in `0.16.x`.

**Comment by bios90** [comment]
I used with two versions 0.16.0.1 and 0.16.0 .Same result on both.

**Comment by ZieIony** [comment]
Okay, so this is an old bug, most likely fixed in the most recent code.

**Comment by bios90** [comment]
Can i use recent release via gradle? I did not find info about newer version(

**Comment by ZieIony** [comment]
You can use https://jitpack.io/#ZieIony/carbon to test the most recent code. Just select 'commits' and 'get it' to get instructions on how to get the most recent version. There was no official release since `0.16.1` because I was changing lots of things and had too many issues to call it stable. Currently, the code in the master branch is quite stable and should be ready to be released.

**Comment by bios90** [comment]
I tried `implementation 'com.github.ZieIony:carbon:d3fdce140e'` but `carbon_elevationShadowColor` still not working on Android 7.0. Maybe it is problem in my device.

**Comment by ZieIony** [comment]
I'll check that.

**Comment by ZieIony** [comment]
I'm not sure if I reproduced and fixed your issue or another one, but colored shadows on API 21-27 were not drawn properly. Not completely missing, but the soft part was not drawn. The fix is in the repository.

**Comment by michaelChicherin** [comment]
Hi ZieIony,

It's not working with last commit, so the fix is not in repository. Shadows still missing if carbon_elevationShadowColor is set.

**Comment by ZieIony** [comment]
False alarm.
